name: release obbinlog-ce

on: 
  push:
    tags: 
      - "obbinlog-ce-*"

env:
  tagName: ${{ github.ref_name }}

jobs:
  release-obbinlog-ce:
    runs-on: ubuntu-latest
    steps:
      # - name: Log in to Docker hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Log in to Quay io
      #   uses: docker/login-action@v3
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.QUAY_IO_USERNAME }}
      #     password: ${{ secrets.QUAY_IO_PASSWORD }}

      # - name: Log in to Ghcr io
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Version variables
        id: set_version_vars
        run: echo "version=$(echo $tagName | grep -P '(\d*\.\d*\.\d*\.\d*-\d*)' --only-matching)" >> $GITHUB_OUTPUT

      - name: Build obbinlog-ce for AMD64
        uses: docker/build-push-action@v6
        with:
          context: ./obbinlog-ce
          platforms: linux/amd64
          file: ./obbinlog-ce/Dockerfile
          push: false
          load: true
          tags: |
            obbinlog-ce:${{ steps.set_version_vars.outputs.version }}-amd64

      - name: Build obbinlog-ce for ARM64
        uses: docker/build-push-action@v6
        with:
          context: ./obbinlog-ce
          platforms: linux/arm64
          file: ./obbinlog-ce/Dockerfile
          push: false
          load: true
          tags: |
            obbinlog-ce:${{ steps.set_version_vars.outputs.version }}-arm64 