name: release obbinlog-cezsdzdzdzdz

on: 
  push:
    tags: 
      - "obbinlog-ce-*"

env:
  tagName: ${{ github.ref_name }}

jobs:
  release-obbinlog-ce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Version variables
        id: set_version_vars
        run: |
          echo "Tag name: $tagName"
          VERSION=$(echo $tagName | sed 's/obbinlog-ce-//')
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version=$(echo $tagName | sed 's/obbinlog-ce-//')" >> $GITHUB_OUTPUT

      - name: Build and push obbinlog-ce w/o cache
        uses: docker/build-push-action@v6
        with:
          context: ./obbinlog-ce
          platforms: linux/amd64,linux/arm64
          file: ./obbinlog-ce/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_PUSH_BASE }}/obbinlog-ce:${{ steps.set_version_vars.outputs.version }}
            quay.io/${{ vars.QUAY_IO_PUSH_BASE }}/obbinlog-ce:${{ steps.set_version_vars.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/obbinlog-ce:${{ steps.set_version_vars.outputs.version }} 